### ISSUE TITLE
replace-last

### ISSUE THREAD

**Issue by expez** [expez/superstring#12]
Sometimes you want to replace the last occurrence.

**Comment by beoliver** [comment]
@expez not sure if you are still interested in this... using the `java.String` methods you can do the following

```clojure
(defn replace-last [^String s ^String match ^String replacement]
  (let [last-index (.lastIndexOf s match)]
    (if (== last-index -1)
      s
      (-> s
          (.substring 0 last-index)
          java.lang.StringBuilder.
          (.append replacement)
          (.append (.substring s (+ last-index (.length match))))
          .toString))))
```

**Comment by beoliver** [comment]
@expez javascript has [lastIndexOf](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/lastIndexOf) and [substring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring) so it should be fairly straightforward.
