### ISSUE TITLE
Probably there is a mistake in `split-words` fn

### ISSUE THREAD

**Issue by galatyn** [expez/superstring#23]
### Steps to reproduce
```clojure
(str/lisp-case "message(SMS)")
=> "message(sm-s)"
```

Actual result: `"message(sm-s)"`
Expected result: `"message(sms)"`

### How to fix
The problem seems to be here:
```clojure
(replace #"(\p{javaUpperCase})((\p{javaUpperCase})[(\p{javaLowerCase})0-9])" "$1 $2")
```
Because this RE `[(\p{javaLowerCase})0-9]` will catch digits, lower cased chars and, I believe unwanted, parentheses `(` `)`.
This probably should be 
`[\p{javaLowerCase}0-9]` instead of
`[(\p{javaLowerCase})0-9]`
Example:
```clojure
(clojure.string/replace "aB()" #"[\p{javaLowerCase}]" "-")
=> "-B()"
(clojure.string/replace "aB()" #"[(\p{javaLowerCase})]" "-")
=> "-B--"
```

**Comment by expez** [comment]
Fixed in release 3.2.1.  Thanks again, @galatyn, and happy new year!
