### ISSUE TITLE
Mismatch in API documentation for `pascal-case`?

### ISSUE THREAD

**Issue by flexibeast** [expez/superstring#4]
The API documentation for `pascal-case` currently states:
```
Lower case first char in s and use capitalization to separate words.

foo bar => FooBar
camelCase => CamelCase
PascalCase => PascalCase
```
The description of "[l]ower case first char" doesn't seem to match the examples.

**Comment by expez** [comment]
Thanks for letting me know, @flexibeast! :+1:
