### ISSUE TITLE
Missing function longest match

### ISSUE THREAD

**Issue by slipset** [expez/superstring#6]
I'm missing a function like 
```
(longest-match "lol-lol--lol---lol-" "-")
;=> 3
```
naive implementation for only chr
```
(defn longest-match [s chr]
   (or (some->> (re-seq (re-pattern (str chr "+")) s)
              (map count)
              (apply max)) 0))
```

**Comment by expez** [comment]
I'm trying to think of situations where "The max number of consecutive repetitions of s1 in s2" is going to be useful and I'm having a really hard time coming up with any. This might be specific to whatever domain you're working on and not something that would see much use in general.
