### ISSUE TITLE
Suggestion: add live documentation with Klipse

### ISSUE THREAD

**Issue by viebel** [expez/superstring#8]
Here is a demo page with live documentation for superstring:
http://viebel.github.io/klipse/examples/superstring.html

More info about klipse: https://github.com/viebel/klipse

**Comment by expez** [comment]
Sure, that looks cool.  Pull-request welcome :)

**Comment by viebel** [comment]
Here you go: https://github.com/expez/superstring/pull/9

**Comment by viebel** [comment]
@expez did you take a look at @ #9 ?

**Comment by expez** [comment]
Yeah it looks cool.  I just haven't had time to set up github pages.  It probably doesn't take long, but I've been kind of swamped.  Sorry for the delay!

**Comment by viebel** [comment]
No problem.
Take your time...

**Comment by viebel** [comment]
There is another way to serve html directly from github. Take a look at https://rawgit.com/

**Comment by expez** [comment]
Documentation is live, it was super easy with rawgit!  Thanks @viebel! 👍
